### ISSUE TITLE
Naidong's suggestions

### ISSUE THREAD

**Issue by liuxiaowen** [liuxiaowen/casms_web_dev#8]
I am wondering whether we should add the link for the past events so that people can register/view the recorded presentations. Currently there are only the copy of the flyers there. I am also thinking it might be also good to add those flyers to the news section.

I assume the new/future events will be added to the top of the existing ones and with links for people to register.

It seems the CASMS link in the event is inactivated. The same for the Gathertown too.

Should we reserve the webinar section just for future CASMS webinars? Currently we listed past conferences there.

Shall we expand the Links to more societies such as CAS, CACA, AAPS etc?

Shall we provide a short instruction in the Job section for the hiring managers/companies/universities for how to contact/provide open jobs? Shall we consider for a small fee for openings from non-CASMS member institutes?

**Comment by JinlanDong** [comment]
Below are what I did and my questions: 
#1. do we have the recorded presentations? I never saw them in the old website either. I would think the news is for external news. if CASMS host any events, they go to events or webinar. So I didn't do anything for this one. 
#2.Webinar tab is updated. CACA uses gotowebinar to host webinars and that platform needs an account. 
#3. There are no links. I didn't understand this question. 
#4. I would think the links are mainly for MS related. So I didn't change it. But I can update it if you think it is good. 
#5. I only added a blank page. not sure what the current practice is.

**Comment by Daniel-Liang-2021** [comment]
To Jinlan's questions:
1. No recorded presentation as of now. No action needed now.
2. Great
3. No action needed.
4. It is okay to add a link to CAS, CACA, AAPS
5. We can ask the executive team to provide an instruction.
